  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  okta:
    issuer: https://dev-14930488.okta.com/oauth2/default 
    audience: api://default
